### ISSUE TITLE
Broken CI job

### ISSUE THREAD

**Issue by valdar** [maximbaz/docker-arch-build-aur#12]
Hello, it seems that your CI job has been broken for some times.

Looking at the error and digging a litel bit I think that this is the cause: https://bugs.archlinux.org/task/69563

and this the workaround https://github.com/qutebrowser/qutebrowser/commit/478e4de7bd1f26bebdcdc166d5369b2b5142c3e2

**Comment by max-baz** [comment]
Many thanks! I knew about the issue, but didn't know there is a workaround! Will apply right away 🙂

**Comment by max-baz** [comment]
Moved to Github actions where this workaround is no longer necessary.

**Comment by valdar** [comment]
Just curiosity: why GH actions are not affected? I seems to remember it was an archlinux + docker issue?

**Comment by max-baz** [comment]
I can't recall where I read it, but it was something about Docker running on old Ubuntu versions that was a true cause of the issue, and I think Github actions contrary to Travis use newer Ubuntu that is compatible with whatever package Arch uses...
