### ISSUE TITLE
Error using `maximbaz/arch-build-aur:latest` build image on fedora

### ISSUE THREAD

**Issue by valdar** [maximbaz/docker-arch-build-aur#13]
I get the following error if I try to use `maximbaz/arch-build-aur:latest` to build my AUR packages:

```bash
error: failed to initialize alpm library
(could not find or read directory: /var/lib/pacman/)
```
the error seems related to #12 in fact if I rebuild the image locally adding:
```dockerfile
# WORKAROUND for glibc 2.33 and old Docker
# See https://github.com/actions/virtual-environments/issues/2658
# Thanks to https://github.com/lxqt/lxqt-panel/pull/1562
RUN patched_glibc=glibc-linux4-2.33-4-x86_64.pkg.tar.zst && \
    curl -LO "https://repo.archlinuxcn.org/x86_64/$patched_glibc" && \
    bsdtar -C / -xvf "$patched_glibc"
```
to the Dockerfile all works as expected...

**Comment by max-baz** [comment]
Hello, if I understood it correctly it's due to a bug in older docker. Would you be able to upgrade docker on your machine and retry?

**Comment by valdar** [comment]
`docker version` says `19.03.11` release date last December, I will try with something newer.

**Comment by valdar** [comment]
Working with docker `20.10.5`.

I missed the part of the issue mentioning an "old" docker version as part of the problem.

Tnx!
