### ISSUE TITLE
Support for building Arch Linux ARM packages

### ISSUE THREAD

**Issue by ghost** [maximbaz/docker-arch-build-aur#15]
Is it possible to build ARM packages?
Thanks

**Comment by max-baz** [comment]
Hello - I don't have a hardware to try on, but I would imagine the image would not be compatible as it is based on official Arch Linux image which in turn is only available as `x86_64` on docker hub. Happy to be proven wrong though!

**Comment by max-baz** [comment]
Closing for now as I don't think it's possible, but to anyone interested who has an idea: PRs welcome 🙂
