### ISSUE TITLE
The CI scheduled actions seems to be disabled

### ISSUE THREAD

**Issue by valdar** [maximbaz/docker-arch-build-aur#16]
I think that due to inactivity in the repo the CI github action has been disabled.

**Comment by max-baz** [comment]
Yeah, I tried to keep it active, but it requires doing manual activity quite often, so I gave up :neutral_face:

**Comment by valdar** [comment]
Do you mind if I try to keep it running on my fork publishing to quay.io repo?

**Comment by max-baz** [comment]
Not at all! Just a note that the issue here is that Github actions stops working after a month of inactivity, not so much the container registry itself.

**Comment by valdar** [comment]
I see. I plan to use quay.io just because is more convenient to me.

**Comment by max-baz** [comment]
You have my blessing :grin: If you ever find a way to make it continuously update, without you doing some manual work every now and then, let me know!

**Comment by valdar** [comment]
> You have my blessing 😁 If you ever find a way to make it continuously update, without you doing some manual work every now and then, let me know!

so it seems I have found a way by adding a specific git hub action step see https://github.com/valdar/docker-arch-build-aur/blob/main/.github/workflows/ci.yml#L25

**Comment by max-baz** [comment]
Hahaha, lovely :joy: 

I feel like it would make sense for us to join efforts. Since you obviously kept it more up-to-date, what do you think about also publishing on docker hub (under your username), and me archiving the project in favour of yours?

**Comment by valdar** [comment]
Sure, I should have done it. The docker hub image can be found here https://hub.docker.com/repository/docker/valdar/arch-build-aur/general

**Comment by max-baz** [comment]
Awesome, thanks, archiving the project then :+1:
