### ISSUE TITLE
Failed to build chromium-vaapi

### ISSUE THREAD

**Issue by azhuchkov** [maximbaz/docker-arch-build-aur#3]
Got a problem about absence of `libffi.so` during build.
Workaround (command to run): `pacman -Syyuu --noconfirm && /build-aur chromium-vaapi`

**Comment by max-baz** [comment]
Hi, that's a strange workaround, could it be that you simply didn't pull the image before trying to build a package?

**Comment by azhuchkov** [comment]
I’ve built the image myself and then used command from the README (eventually failed).

I’m not experienced in Arch, but it looks like building process requires system update before launch.

**Comment by max-baz** [comment]
Gotcha. If you are building the image yourself, then you must ensure you pull the base image before building, to ensure the base image is updated - in this case it's defined here:

https://github.com/maximbaz/docker-arch-build-aur/blob/3325f94e2f13be43844623475d442e2e1790cf95/Dockerfile#L1

So `docker pull archlinux/base:latest` and then build your image.

---

To take care of this, my image is being built daily by Travis, to make sure its dependencies are always up-to-date.

**Comment by azhuchkov** [comment]
This is what I have:

```
$ docker image ls
REPOSITORY                TAG                 IMAGE ID            CREATED             SIZE
maximbaz/arch-build-aur   latest              412e91ee94c9        5 hours ago         893MB
archlinux                 latest              9651b9e35f39        2 weeks ago         412MB
archlinux/base            latest              345c9418cf48        3 weeks ago         502MB
...
```

I suppose it's the latest version which was pulled automatically during building your image.

**Comment by azhuchkov** [comment]
Also I tried pulling image instead of building it - the result was the same.

**Comment by max-baz** [comment]
`docker build` doesn't pull updates to dependencies (it pulls them once only if they are entirely missing from your system), so you can see that archlinux/base is 3 weeks old, probably because 3 weeks ago you tried to build this image for the first time?

**Comment by azhuchkov** [comment]
I have never used Arch inside docker. And didn't used docker for months. And I tried to build chromium-vaapi from 2 different machines, and 1 of them was fresh cloud server.

**Comment by max-baz** [comment]
Ha, the base image itself stopped being update, https://hub.docker.com/r/archlinux/base/tags says it wasnt updated for 24 days! In that case sure, lets take your suggestion 👍

**Comment by max-baz** [comment]
Should be fixed with https://github.com/maximbaz/docker-arch-build-aur/commit/f9d7787b9171a9646d8811569a3d37cf36eac7ba, thank you very much for letting me know about this problem!

**Comment by azhuchkov** [comment]
Thanks for the image that allows to easily build heavy packages on dedicated hardware! I suppose it saved me many hours of CPU time.
