### ISSUE TITLE
Few tips & tricks regarding docker image

### ISSUE THREAD

**Issue by erkexzcx** [maximbaz/docker-arch-build-aur#4]
Hey.

Check out my fork of your repo. Everything is the same, except this part: https://github.com/erkexzcx/docker-arch-build-aur/blob/master/Dockerfile#L3L5

- `pacman -S --noconfirm pacman-mirrorlist` is needed otherwise when I try to compile a kernel, it tries to download multiple dependencies. Some of them, for unknown reason, fail to retrieve (e.g. `imagemagick`). It turned out that I have to force reinstall `pacman-mirrorlist` so it's kind of forced mirrorlist refresh. This step fixed the problem to me.

- `sed -i 's/#MAKEFLAGS="-j2"/MAKEFLAGS="-j$(nproc)"/' /etc/makepkg.conf` basically replaces `#MAKEFLAGS="-j2"` with `MAKEFLAGS="-j$(nproc)"` in `/etc/makepkg.conf` so docker image uses all available cores when compiling certain apps.

**Comment by erkexzcx** [comment]
Feel free to add these changes yourself, o let me know if you want to receive pull request. :)

**Comment by max-baz** [comment]
Hey, thanks for this :)

- `pacman -S --noconfirm pacman-mirrorlist` is ... weird, I would like to better understand _why_ this helps.... Isn't `pacman -Syu --noconfirm` supposed to update mirrorlist package if there is an update? And if there is no update, reinstalling mirrorlist should do nothing? 🤔 If you still can reproduce this, can you see if `pacman -Syu` somehow skips that package, and if `pacman -S --noconfirm pacman-mirrorlist` does install a new version?

- `MAKEFLAGS="-j$(nproc)"` - totally agree, but a nicer way of doing this would be `RUN echo 'MAKEFLAGS="-j$(nproc)"' > /home/makepkg/.config/pacman/makepkg.conf` - at least this is what I have locally 😄 

Would love a PR for the second point (maybe after we figure out the first one?), and while we are at it, I think we could also reduce amount of `RUN` statements to remove some layers...

**Comment by max-baz** [comment]
I had the time to push updates for the second point, if you have time to investigate the issue with pacman-mirrorlist, do ping me 👍
